### ISSUE TITLE
Commands aren't working

### ISSUE THREAD

**Issue by timothy-kumm** [AcidProxy/Acid#5]
So the commands arent working ingame.

**Comment by boi1216** [comment]
this is already known issue, commands will be added in rewrite of proxy

**Comment by GamakCZ** [comment]
To debug this problem, you can use older version of [Acid](https://github.com/AcidProxy/Acid/archive/12060144794dd92cc04def603443f81605555a69.zip)

**Comment by TimmYCode** [comment]
And how can I install older versions ?

**Comment by GamakCZ** [comment]
fixed
