### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by 4ifi** [AcidProxy/Acid#6]
Fatal error: Uncaught TypeError: Return value of pocketmine\utils\MainLogger::getLogger() must be an instance of pocketmine\utils\MainLogger, null returned in /home/user/Acid/vendor/pocketmine/pocketmine-mp/src/pocketmine/utils/MainLogger.php:77
Stack trace:
#0 /home/user/Acid/vendor/pocketmine/pocketmine-mp/src/pocketmine/network/mcpe/protocol/LoginPacket.php(89): pocketmine\utils\MainLogger::getLogger()
#1 /home/user/Acid/vendor/pocketmine/pocketmine-mp/src/pocketmine/network/mcpe/protocol/DataPacket.php(71): pocketmine\network\mcpe\protocol\LoginPacket->decodePayload()
#2 /home/user/Acid/src/proxy/network/UpstreamAbstractConnection.php(73): pocketmine\network\mcpe\protocol\DataPacket->decode()
#3 /home/user/Acid/src/proxy/ProxyServer.php(268): proxy\network\UpstreamAbstractConnection->handlePacket(Object(pocketmine\network\mcpe\protocol\LoginPacket))
#4 /home/user/Acid/src/proxy/ProxyServer.php(251): proxy\ProxyServer->getPacket('\x8C\x08\x00\x00p"\xC0\x07\x00\x00\x01\x00\x00\x00\x00...', Object(proxy\network\Downstrea in /home/user/Acid/vendor/pocketmine/pocketmine-mp/src/pocketmine/utils/MainLogger.php on line 77

**Comment by GamakCZ** [comment]
Pocketmine issue
